package com.jirofeingold.pairfortwo.ui.theme

import androidx.compose.ui.graphics.Color

// GENERATED by tools/generate_colors.py from the iOS app's Themes.swift.
// Do not edit by hand — re-run the script instead. See PLAN.md §6.

// ---- Felt palette ----

val FeltDark = Color(0xFF0D211A)
val FeltMid = Color(0xFF173326)
val CribGold = Color(0xFFF0C973)
val CardFace = Color(0xFFFAF6E6)
val CardInk = Color(0xFF1F1F24)
val CardRed = Color(0xFFCC1F29)
val CardBackNavy = Color(0xFF1A3873)

// ---- Player themes ----

/** One of the twelve peg colours a player can pick. Must stay in sync with iOS. */
data class PlayerTheme(
    val id: String,
    val displayName: String,
    val primary: Color,
    val deep: Color,
)

val playerThemes: List<PlayerTheme> = listOf(
    PlayerTheme("crimson", "Crimson", Color(0xFFFF2E47), Color(0xFFC70F24)),
    PlayerTheme("coral", "Coral", Color(0xFFFF804C), Color(0xFFD14C1A)),
    PlayerTheme("tangerine", "Tangerine", Color(0xFFFF9E1A), Color(0xFFD9660A)),
    PlayerTheme("gold", "Gold", Color(0xFFFFD926), Color(0xFFC79405)),
    PlayerTheme("lime", "Lime", Color(0xFF8CF22E), Color(0xFF4CA614)),
    PlayerTheme("mint", "Mint", Color(0xFF29EB80), Color(0xFF0D9E4C)),
    PlayerTheme("teal", "Teal", Color(0xFF1AE0D9), Color(0xFF058C9E)),
    PlayerTheme("sky", "Sky", Color(0xFF2EA8FF), Color(0xFF0F5CD9)),
    PlayerTheme("indigo", "Indigo", Color(0xFF665CFF), Color(0xFF3329CC)),
    PlayerTheme("plum", "Plum", Color(0xFFC747FF), Color(0xFF8C1ACC)),
    PlayerTheme("magenta", "Magenta", Color(0xFFFF38D1), Color(0xFFC70F94)),
    PlayerTheme("rose", "Rose", Color(0xFFFF73AD), Color(0xFFD13373)),
)

/** Maps the model's integer colorID onto a theme (wraps around the palette). */
fun playerTheme(colorID: Int): PlayerTheme =
    playerThemes[((colorID % playerThemes.size) + playerThemes.size) % playerThemes.size]
