#!/usr/bin/env python3
"""Generate ui/theme/Color.kt from the iOS app's Themes.swift.

The palette is shared identity between the two apps, so it is generated rather than
hand-transcribed — 31 colours retyped by hand is 31 chances to be one digit off.

Re-run after any palette change on iOS:

    python3 tools/generate_colors.py

SwiftUI's `Color(red:green:blue:)` and Compose's `Color(0xAARRGGBB)` are both sRGB, so
each float component maps to the nearest 8-bit value.
"""

import re
import pathlib
import sys

IOS_THEMES = pathlib.Path(
    "~/Projects/Pair for two/Pair for two/Themes.swift"
).expanduser()

OUT = pathlib.Path(__file__).parent.parent / (
    "app/src/main/kotlin/com/jirofeingold/pairfortwo/ui/theme/Color.kt"
)

# Swift namespaces `Color.cardBack` and `enum CardBack` separately; Kotlin top-level
# declarations in one package would collide. Rename the colour, keep `CardBack` free
# for the card-back design enum.
RENAME = {"cardBack": "cardBackNavy"}

COLOR = r"Color\(red:\s*([\d.]+),\s*green:\s*([\d.]+),\s*blue:\s*([\d.]+)\)"


def hexc(r: str, g: str, b: str) -> str:
    f = lambda v: max(0, min(255, int(round(float(v) * 255))))
    return "0xFF%02X%02X%02X" % (f(r), f(g), f(b))


def main() -> int:
    if not IOS_THEMES.exists():
        print(f"error: iOS source not found at {IOS_THEMES}", file=sys.stderr)
        return 1
    src = IOS_THEMES.read_text()

    base = re.findall(r"static let (\w+)\s*=\s*" + COLOR, src)
    themes = re.findall(
        r'\.init\(id:\s*"(\w+)",\s*displayName:\s*"([^"]+)",\s*primary:\s*'
        + COLOR
        + r",\s*deep:\s*"
        + COLOR,
        src,
    )

    # Fail loudly rather than silently emitting a half-empty palette if the Swift
    # formatting changes and the regexes stop matching.
    if len(base) != 7:
        print(f"error: expected 7 base colours, found {len(base)}", file=sys.stderr)
        return 1
    if len(themes) != 12:
        print(f"error: expected 12 player themes, found {len(themes)}", file=sys.stderr)
        return 1

    out = [
        "package com.jirofeingold.pairfortwo.ui.theme",
        "",
        "import androidx.compose.ui.graphics.Color",
        "",
        "// GENERATED by tools/generate_colors.py from the iOS app's Themes.swift.",
        "// Do not edit by hand — re-run the script instead. See PLAN.md §6.",
        "",
        "// ---- Felt palette ----",
        "",
    ]
    for name, r, g, b in base:
        name = RENAME.get(name, name)
        out.append(f"val {name[0].upper()}{name[1:]} = Color({hexc(r, g, b)})")

    out += [
        "",
        "// ---- Player themes ----",
        "",
        "/** One of the twelve peg colours a player can pick. Must stay in sync with iOS. */",
        "data class PlayerTheme(",
        "    val id: String,",
        "    val displayName: String,",
        "    val primary: Color,",
        "    val deep: Color,",
        ")",
        "",
        "val playerThemes: List<PlayerTheme> = listOf(",
    ]
    for tid, disp, pr, pg, pb, dr, dg, db in themes:
        out.append(
            f'    PlayerTheme("{tid}", "{disp}", '
            f"Color({hexc(pr, pg, pb)}), Color({hexc(dr, dg, db)})),"
        )
    out += [
        ")",
        "",
        "/** Maps the model's integer colorID onto a theme (wraps around the palette). */",
        "fun playerTheme(colorID: Int): PlayerTheme =",
        "    playerThemes[((colorID % playerThemes.size) + playerThemes.size) % playerThemes.size]",
        "",
    ]

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(pathlib.Path.cwd())}: "
          f"{len(base)} base colours, {len(themes)} player themes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
