package com.jirofeingold.pairfortwo.core

import java.io.File
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.encodeToJsonElement
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestFactory

/**
 * Asserts this module both **accepts** and **produces** the exact shapes the iOS app does.
 *
 * The fixtures in `fixtures/protocol-v1/` were generated by the iOS implementation
 * (`tools/verify-protocol.sh` in that repo). They are the contract: if Kotlin can round-trip
 * every one of them without changing the JSON tree, the two apps can talk.
 *
 * Comparison is on re-parsed values rather than raw bytes — per PROTOCOL.md, formatting is not
 * part of the contract, but key presence, key names, types, and array order are.
 */
class ProtocolFixtureTest {

    private val fixtureDir = File("../fixtures/protocol-v1")

    /** Every message type in the sealed hierarchy, so a new one can't be silently untested. */
    private val expected = setOf(
        "hello", "assignSeat", "snapshot",
        "intentCut", "intentDiscard", "intentPlay", "intentGo",
        "intentLiftCut", "intentRevealStarter",
        "claimPoints", "undo", "advance", "playAgain",
        "updateIdentity", "setScoringMode", "quitGame",
    )

    private fun fixtures(): List<File> =
        fixtureDir.listFiles { f: File -> f.extension == "json" }?.sortedBy { it.name } ?: emptyList()

    @Test
    fun `every message type has a fixture`() {
        assertTrue(fixtureDir.isDirectory, "fixtures not found at ${fixtureDir.absolutePath}")
        assertEquals(expected, fixtures().map { it.nameWithoutExtension }.toSet())
    }

    /**
     * One test per fixture, so a failure names the offending message type rather than just
     * "the protocol test failed".
     */
    @TestFactory
    fun `fixture round-trips unchanged`(): List<DynamicTest> = fixtures().map { file ->
        DynamicTest.dynamicTest(file.nameWithoutExtension) {
            val onDisk = Json.parseToJsonElement(file.readText())

            // Accept: the iOS bytes must decode.
            val message = PairWireJson.decodeFromString<GameMessage>(file.readText())

            // Produce: re-encoding must yield the same tree, not merely something decodable.
            val reEncoded: JsonElement = PairWireJson.encodeToJsonElement(message)
            assertEquals(onDisk, reEncoded, "re-encoding ${file.name} changed the JSON")
        }
    }

    @Test
    fun `hello announces the protocol version`() {
        val hello = PairWireJson.decodeFromString<GameMessage>(
            File(fixtureDir, "hello.json").readText()
        )
        assertEquals(WIRE_PROTOCOL_VERSION, (hello as GameMessage.Hello).protocol)
    }

    @Test
    fun `snapshot fixture preserves every field iOS sent`() {
        val decoded = PairWireJson.decodeFromString<GameMessage>(
            File(fixtureDir, "snapshot.json").readText()
        ) as GameMessage.Snapshot
        val s = decoded.snapshot

        // Spot-check the fields whose encodings differ between the two languages.
        assertEquals("6ba7b810-9dad-11d1-80b4-00c04fd430c8", s.matchID)
        assertEquals(ScoringMode.FEEDBACK, s.scoringMode)
        assertEquals(GamePhase.PEGGING, s.phase)
        assertEquals(setOf(PlayerID.ONE, PlayerID.TWO), s.playersWithClaims)
        assertEquals(
            mapOf(
                PlayerID.ONE to Card(Rank.THREE, Suit.HEARTS),
                PlayerID.TWO to Card(Rank.QUEEN, Suit.CLUBS),
            ),
            s.cutForDeal,
        )
        assertEquals(Card(Rank.JACK, Suit.SPADES), s.starter)
        assertEquals(PegEvent(PegEvent.Kind.THIRTY_ONE, PlayerID.ONE, 2), s.lastPegEvent)
        assertEquals(ScoreFlag.Kind.HIS_HEELS, s.flags[1].kind)
        // Absent optionals decoded as null rather than being invented.
        assertEquals(null, s.opponentHand)
        assertEquals(null, s.crib)
        assertEquals(null, s.winner)
    }

    @Test
    fun `unknown keys from a newer peer are ignored`() {
        val withExtra = """{"t":"intentCut","index":7,"somethingNew":true}"""
        assertEquals(
            GameMessage.IntentCut(7),
            PairWireJson.decodeFromString<GameMessage>(withExtra),
        )
    }
}
